# Generated by Django 4.1.4 on 2022-12-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_remove_doctor_login_remove_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeOfVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'purpose_of_visit',
            },
        ),
        migrations.AlterField(
            model_name='reception',
            name='purpose_of_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.purposeofvisit'),
        ),
    ]
